apiVersion: apps/v1
kind: Deployment
metadata:
  name: %{service_name}
  namespace: %{team_ns}
spec:
  selector:
    matchLabels:
      app: %{service_name}
  replicas: %{replicas}
  template:
    metadata:
      labels:
        app: %{service_name}
    spec:
      containers:
        - name: %{service_name}
          image: %{docker_hub}/platform/%{service_name}:%{build_tag}
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: java-opts
          env:
            - name: TZ
              value: Asia/Shanghai
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: %{live_path}
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 3
            timeoutSeconds: 1
          readinessProbe:
            httpGet:
              path: %{live_path}
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 1
          resources:
            requests:
              memory: "256Mi"
            limits:
              memory: "%{memory_max}"
          volumeMounts:
            - name: %{service_name}
              mountPath: %{app_path}/logs
              subPath: %{service_name}/logs
            - name: %{service_name}
              mountPath: %{app_path}/balance_file
              subPath: %{service_name}/files
            - name: %{service_name}
              mountPath: %{app_path}/temp
              subPath: %{service_name}/temp
            - name: yunst-cert
              mountPath: %{app_path}/yunst
      volumes:
        - name: %{service_name}
          flexVolume:
            driver: ceph.rook.io/rook
            fsType: ceph
            options:
              fsName: myfs
              clusterNamespace: rook-ceph
        - name: yunst-cert
          configMap:
            name: yunst-cert