apiVersion: apps/v1
kind: Deployment
metadata:
  name: %{service_name}
  namespace: %{team_ns}
spec:
  selector:
    matchLabels:
      app: %{service_name}
  replicas: %{replicas}
  template:
    metadata:
      labels:
        app: %{service_name}
    spec:
      containers:
        - name: %{service_name}
          image: %{docker_hub}/platform/%{service_name}:%{build_tag}
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: java-opts
          env:
            - name: TZ
              value: Asia/Shanghai
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: %{live_path}
              port: 8080
            initialDelaySeconds: 120
            periodSeconds: 3
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: %{live_path}
              port: 8080
            initialDelaySeconds: 120
            periodSeconds: 10
            timeoutSeconds: 5
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh", "-c", "sleep 30"]
          resources:
            requests:
              cpu: "5m"
              memory: "256Mi"
            limits:
#              cpu: "500m"
              memory: "%{memory_max}"
          volumeMounts:
            - name: %{service_name}-logs
              mountPath: %{app_path}/logs
            - name: yunst-cert
              mountPath: %{app_path}/yunst
            - name: %{service_name}-ceph
              mountPath: %{app_path}/balance_file
              subPath: %{service_name}/files/balance_file
      volumes:
        - name: %{service_name}-logs
          hostPath:
            path: /data/logs/%{log_pre_path}%{team_ns}-%{service_name}
            type: Directory
        - name: yunst-cert
          configMap:
            name: yunst-cert
        - name: %{service_name}-ceph
          flexVolume:
            driver: ceph.rook.io/rook
            fsType: ceph
            options:
              fsName: myfs
              clusterNamespace: rook-ceph